<?php

/**
 * This is the model base class for the table "tipo_aula_has_disciplina".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TipoAulaHasDisciplina".
 *
 * Columns in table "tipo_aula_has_disciplina" available as properties of the model,
 * followed by relations of table "tipo_aula_has_disciplina" available as properties of the model.
 *
 * @property integer $id
 * @property integer $disciplina_id
 * @property integer $tipo_aula_id
 * @property integer $carga_horaria
 *
 * @property Disciplina $disciplina
 * @property TipoAula $tipoAula
 */
abstract class BaseTipoAulaHasDisciplina extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'tipo_aula_has_disciplina';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TipoAulaHasDisciplina|TipoAulaHasDisciplinas', $n);
	}

	public static function representingColumn() {
		return 'id';
	}

	public function rules() {
		return array(
			array('disciplina_id', 'required'),
			array('disciplina_id, tipo_aula_id, carga_horaria', 'numerical', 'integerOnly'=>true),
			array('tipo_aula_id, carga_horaria', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, disciplina_id, tipo_aula_id, carga_horaria', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'disciplina' => array(self::BELONGS_TO, 'Disciplina', 'disciplina_id'),
			'tipoAula' => array(self::BELONGS_TO, 'TipoAula', 'tipo_aula_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'disciplina_id' => null,
			'tipo_aula_id' => null,
			'carga_horaria' => Yii::t('app', 'Carga Horaria'),
			'disciplina' => null,
			'tipoAula' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('disciplina_id', $this->disciplina_id);
		$criteria->compare('tipo_aula_id', $this->tipo_aula_id);
		$criteria->compare('carga_horaria', $this->carga_horaria);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}