<?php

/**
 * This is the model base class for the table "periodo".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Periodo".
 *
 * Columns in table "periodo" available as properties of the model,
 * followed by relations of table "periodo" available as properties of the model.
 *
 * @property integer $id
 * @property string $descricao
 *
 * @property PpcHasTipoDisciplinaHasDisciplina[] $ppcHasTipoDisciplinaHasDisciplinas
 */
abstract class BasePeriodo extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'periodo';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Periodo|Periodos', $n);
	}

	public static function representingColumn() {
		return 'descricao';
	}

	public function rules() {
		return array(
			array('id', 'required'),
			array('id', 'numerical', 'integerOnly'=>true),
			array('descricao', 'length', 'max'=>45),
			array('descricao', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, descricao', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ppcHasTipoDisciplinaHasDisciplinas' => array(self::HAS_MANY, 'PpcHasTipoDisciplinaHasDisciplina', 'periodo_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'descricao' => Yii::t('app', 'Descricao'),
			'ppcHasTipoDisciplinaHasDisciplinas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('descricao', $this->descricao, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}