<?php

/**
 * This is the model base class for the table "ppc".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Ppc".
 *
 * Columns in table "ppc" available as properties of the model,
 * followed by relations of table "ppc" available as properties of the model.
 *
 * @property integer $id
 * @property integer $curso_id
 * @property integer $situacao_id
 * @property string $numero
 * @property integer $carga_horaria_total_curso
 * @property integer $credito_total
 *
 * @property Curso $curso
 * @property Situacao $situacao
 * @property PpcHasTipoDisciplina[] $ppcHasTipoDisciplinas
 */
abstract class BasePpc extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ppc';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Ppc|Ppcs', $n);
	}

	public static function representingColumn() {
		return 'numero';
	}

	public function rules() {
		return array(
			array('curso_id, situacao_id, numero', 'required'),
			array('curso_id, situacao_id, carga_horaria_total_curso, credito_total', 'numerical', 'integerOnly'=>true),
			array('numero', 'length', 'max'=>20),
			array('carga_horaria_total_curso, credito_total', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, curso_id, situacao_id, numero, carga_horaria_total_curso, credito_total', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'curso' => array(self::BELONGS_TO, 'Curso', 'curso_id'),
			'situacao' => array(self::BELONGS_TO, 'Situacao', 'situacao_id'),
			'ppcHasTipoDisciplinas' => array(self::HAS_MANY, 'PpcHasTipoDisciplina', 'ppc_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'curso_id' => null,
			'situacao_id' => null,
			'numero' => Yii::t('app', 'Numero'),
			'carga_horaria_total_curso' => Yii::t('app', 'Carga Horaria Total Curso'),
			'credito_total' => Yii::t('app', 'Credito Total'),
			'curso' => null,
			'situacao' => null,
			'ppcHasTipoDisciplinas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('curso_id', $this->curso_id);
		$criteria->compare('situacao_id', $this->situacao_id);
		$criteria->compare('numero', $this->numero, true);
		$criteria->compare('carga_horaria_total_curso', $this->carga_horaria_total_curso);
		$criteria->compare('credito_total', $this->credito_total);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}