<?php

/**
 * This is the model base class for the table "ppc_has_tipo_disciplina".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PpcHasTipoDisciplina".
 *
 * Columns in table "ppc_has_tipo_disciplina" available as properties of the model,
 * followed by relations of table "ppc_has_tipo_disciplina" available as properties of the model.
 *
 * @property integer $id
 * @property integer $ppc_id
 * @property integer $tipo_disciplina_id
 * @property integer $carga_horaria_total_tipo_disciplina
 *
 * @property Ppc $ppc
 * @property TipoDisciplina $tipoDisciplina
 * @property PpcHasTipoDisciplinaHasDisciplina[] $ppcHasTipoDisciplinaHasDisciplinas
 */
abstract class BasePpcHasTipoDisciplina extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ppc_has_tipo_disciplina';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'PPC tem tipo|PPC têm tipos', $n);
	}

	public static function representingColumn() {
		return 'tipoDisciplina';
	}

	public function rules() {
		return array(
			array('ppc_id, tipo_disciplina_id', 'required'),
			array('ppc_id, tipo_disciplina_id, carga_horaria_total_tipo_disciplina', 'numerical', 'integerOnly'=>true),
			array('carga_horaria_total_tipo_disciplina', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, ppc_id, tipo_disciplina_id, carga_horaria_total_tipo_disciplina', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'ppc' => array(self::BELONGS_TO, 'Ppc', 'ppc_id'),
			'tipoDisciplina' => array(self::BELONGS_TO, 'TipoDisciplina', 'tipo_disciplina_id'),
			'ppcHasTipoDisciplinaHasDisciplinas' => array(self::HAS_MANY, 'PpcHasTipoDisciplinaHasDisciplina', 'ppc_has_tipo_disciplina_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ppc_id' => null,
			'tipo_disciplina_id' => null,
			'carga_horaria_total_tipo_disciplina' => Yii::t('app', 'Carga Horaria Total Tipo Disciplina'),
			'ppc' => null,
			'tipoDisciplina' => null,
			'ppcHasTipoDisciplinaHasDisciplinas' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ppc_id', $this->ppc_id);
		$criteria->compare('tipo_disciplina_id', $this->tipo_disciplina_id);
		$criteria->compare('carga_horaria_total_tipo_disciplina', $this->carga_horaria_total_tipo_disciplina);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}