<?php

/**
 * This is the model base class for the table "ppc_has_tipo_disciplina_has_disciplina".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "PpcHasTipoDisciplinaHasDisciplina".
 *
 * Columns in table "ppc_has_tipo_disciplina_has_disciplina" available as properties of the model,
 * followed by relations of table "ppc_has_tipo_disciplina_has_disciplina" available as properties of the model.
 *
 * @property integer $id
 * @property integer $ppc_has_tipo_disciplina_id
 * @property integer $disciplina_id
 * @property integer $periodo_id
 * @property integer $situacao_curriculo_id
 *
 * @property Disciplina $disciplina
 * @property Periodo $periodo
 * @property PpcHasTipoDisciplina $ppcHasTipoDisciplina
 * @property SituacaoCurriculo $situacaoCurriculo
 */
abstract class BasePpcHasTipoDisciplinaHasDisciplina extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'ppc_has_tipo_disciplina_has_disciplina';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Disciplina do PPC por Tipo|Disciplinas do PPC por Tipo', $n);
	}

	public static function representingColumn() {
		return 'disciplina';
	}

	public function rules() {
		return array(
			array('ppc_has_tipo_disciplina_id, disciplina_id, periodo_id, situacao_curriculo_id', 'required'),
			array('ppc_has_tipo_disciplina_id, disciplina_id, periodo_id, situacao_curriculo_id', 'numerical', 'integerOnly'=>true),
			array('id, ppc_has_tipo_disciplina_id, disciplina_id, periodo_id, situacao_curriculo_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'disciplina' => array(self::BELONGS_TO, 'Disciplina', 'disciplina_id'),
			'periodo' => array(self::BELONGS_TO, 'Periodo', 'periodo_id'),
			'ppcHasTipoDisciplina' => array(self::BELONGS_TO, 'PpcHasTipoDisciplina', 'ppc_has_tipo_disciplina_id'),
			'situacaoCurriculo' => array(self::BELONGS_TO, 'SituacaoCurriculo', 'situacao_curriculo_id'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'ppc_has_tipo_disciplina_id' => null,
			'disciplina_id' => null,
			'periodo_id' => null,
			'situacao_curriculo_id' => null,
			'disciplina' => null,
			'periodo' => null,
			'ppcHasTipoDisciplina' => null,
			'situacaoCurriculo' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('ppc_has_tipo_disciplina_id', $this->ppc_has_tipo_disciplina_id);
		$criteria->compare('disciplina_id', $this->disciplina_id);
		$criteria->compare('periodo_id', $this->periodo_id);
		$criteria->compare('situacao_curriculo_id', $this->situacao_curriculo_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}